### ISSUE TITLE
Strange IllegalStateException in FutureProxy

### ISSUE THREAD

**Issue by fviale** [ow2-proactive/programming#1308]
The following stack trace appears repeatedly in the logs provided by a client (version 6.3.1), then disappears:

```
[2015-12-15 23:15:19,791 ERROR                 p.e.send_reply] pnp://172.16.15.193:64738/RM_NODE/ActiveObject_org.ow2.proactive.resourcemanager.core.RMCore_-55ebdadb-1518721cad7--7ff7--f52c081e4af533a0--55ebdadb-1518721cad7--8000 : Failed to send reply to method:setNodeAvailable sequence: 1318030491 by pnp://172.16.15.202:1101/HalfbodiesNode_848465353/org.objectweb.proactive.core.body.UniversalBodyRemoteObjectAdapter@206f7cea
java.lang.IllegalStateException: FutureProxy receives a reply and the current target field is not null. Current target is [ex:org.objectweb.proactive.core.body.exceptions.FutureMonitoringPingFailureException] while reply's target is [org.objectweb.proactive.core.util.wrapper.BooleanWrapper]
    at org.objectweb.proactive.core.body.future.FutureProxy.receiveReply(FutureProxy.java:231)
    at org.objectweb.proactive.core.body.future.FuturePool.receiveFutureValue(FuturePool.java:270)
    at org.objectweb.proactive.core.body.reply.ReplyReceiverImpl.receiveReply(ReplyReceiverImpl.java:48)
    at org.objectweb.proactive.core.body.HalfBody.internalReceiveReply(HalfBody.java:137)
    at org.objectweb.proactive.core.body.AbstractBody.receiveReply(AbstractBody.java:245)
    at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:353)
    at org.objectweb.proactive.core.remoteobject.RemoteObjectImpl.receiveMessage(RemoteObjectImpl.java:92)
    at org.objectweb.proactive.core.remoteobject.InternalRemoteRemoteObjectImpl.receiveMessage(InternalRemoteRemoteObjectImpl.java:134)
    at org.objectweb.proactive.extensions.pnp.PNPROMessageRequest.processMessage(PNPROMessageRequest.java:102)
    at org.objectweb.proactive.extensions.pnp.PNPServerHandler$RequestExecutor.run(PNPServerHandler.java:280)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by fviale** [comment]
Appeared again in version 7.11:
```
c96f45aaece8b9de-6aba6365-15bb01f7287--8000 : Failed to send reply to method:setNodeAvailable sequence: 1614720178 by pnp://xstoocky07.mgps.inra.fr:45744/Node632611962/org.objectweb.proactive.core.body.UniversalBodyRemoteObjectAdapter@1fd7f37d
java.lang.IllegalStateException: FutureProxy receives a reply and the current target field is not null. Current target is [ex:org.objectweb.proactive.core.body.exceptions.FutureMonitoringPingFailureException] while reply's target is [org.objectweb.proactive.core.util.wrapper.BooleanWrapper]
	at org.objectweb.proactive.core.body.future.FutureProxy.receiveReply(FutureProxy.java:231)
	at org.objectweb.proactive.core.body.future.FuturePool.receiveFutureValue(FuturePool.java:270)
	at org.objectweb.proactive.core.body.reply.ReplyReceiverImpl.receiveReply(ReplyReceiverImpl.java:48)
	at org.objectweb.proactive.core.body.BodyImpl.internalReceiveReply(BodyImpl.java:238)
	at org.objectweb.proactive.core.body.AbstractBody.receiveReply(AbstractBody.java:245)
	at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:353)
	at org.objectweb.proactive.core.remoteobject.RemoteObjectImpl.receiveMessage(RemoteObjectImpl.java:92)
	at org.objectweb.proactive.core.remoteobject.InternalRemoteRemoteObjectImpl.receiveMessage(InternalRemoteRemoteObjectImpl.java:134)
	at org.objectweb.proactive.extensions.pnp.PNPROMessageRequest.processMessage(PNPROMessageRequest.java:102)
	at org.objectweb.proactive.extensions.pnp.PNPServerHandler$RequestExecutor.run(PNPServerHandler.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by fviale** [comment]
Maybe it is related to the following exception, raised right after the first message:
```
[2017-04-29 08:44:49,847 WARN                             /rm] Exception while dispatching incoming RPC call
com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract java.lang.String org.ow2.proactive_grid_cloud_portal.rm.client.RMService.getStatHistory(java.lang.String,java.lang.String) throws org.ow2.proactive_grid_cloud_portal.common.shared.RestServerException,org.ow2.proactive_grid_cloud_portal.common.shared.ServiceException' threw an unexpected exception: javax.ws.rs.client.ResponseProcessingException: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:415)
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:605)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.ws.rs.client.ResponseProcessingException: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:141)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.BodyEntityExtractor.extractEntity(BodyEntityExtractor.java:60)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:104)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
	at com.sun.proxy.$Proxy327.getStatHistory(Unknown Source)
	at org.ow2.proactive_grid_cloud_portal.rm.server.RMServiceImpl$17.apply(RMServiceImpl.java:464)
	at org.ow2.proactive_grid_cloud_portal.rm.server.RMServiceImpl$17.apply(RMServiceImpl.java:461)
	at org.ow2.proactive_grid_cloud_portal.rm.server.RMServiceImpl.executeFunctionReturnStreamAsString(RMServiceImpl.java:526)
	at org.ow2.proactive_grid_cloud_portal.rm.server.RMServiceImpl.getStatHistory(RMServiceImpl.java:461)
	at sun.reflect.GeneratedMethodAccessor336.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
	... 25 more
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
[2017-04-29 08:44:49,841 ERROR               o.o.p.r.c.RMCore] Cannot serve request: method=setNodeAvailable, sender=ActiveObject_org.ow2.proactive.resourcemanager.utils.RMNodeStarter_-7426b41a-15bb01f99ab--7fff--f07036922c9abb2a--7426b41a-15bb01f99ab--8000, sequenceNumber=1614720228
java.lang.OutOfMemoryError: GC overhead limit exceeded
```

**Comment by fviale** [comment]
Actually, this IllegalStateException occurred a few hours before the first OutOfMemoryError:

```
[2017-04-29 02:56:24,790 ERROR                 p.e.send_reply] pnp://138.102.172.34:64738/RM_NODE/ActiveObject_org.ow2.proactive.resourcemanager.core.RMCore_6aba6365-15bb01f7287--7ff7--c96f45aaece8b9de-6aba6365-15bb01f7287--8000 : Failed to send reply to method:setNodeAvailable sequence: 1614719708 by pnp://xstoocky07.mgps.inra.fr:45744/Node632611962/org.objectweb.proactive.core.body.UniversalBodyRemoteObjectAdapter@1fd7f37d
java.lang.IllegalStateException: FutureProxy receives a reply and the current target field is not null. Current target is [ex:org.objectweb.proactive.core.body.exceptions.FutureMonitoringPingFailureException] while reply's target is [org.objectweb.proactive.core.util.wrapper.BooleanWrapper]
	at org.objectweb.proactive.core.body.future.FutureProxy.receiveReply(FutureProxy.java:231)
	at org.objectweb.proactive.core.body.future.FuturePool.receiveFutureValue(FuturePool.java:270)
	at org.objectweb.proactive.core.body.reply.ReplyReceiverImpl.receiveReply(ReplyReceiverImpl.java:48)
	at org.objectweb.proactive.core.body.BodyImpl.internalReceiveReply(BodyImpl.java:238)
	at org.objectweb.proactive.core.body.AbstractBody.receiveReply(AbstractBody.java:245)
	at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:353)
	at org.objectweb.proactive.core.remoteobject.RemoteObjectImpl.receiveMessage(RemoteObjectImpl.java:92)
	at org.objectweb.proactive.core.remoteobject.InternalRemoteRemoteObjectImpl.receiveMessage(InternalRemoteRemoteObjectImpl.java:134)
	at org.objectweb.proactive.extensions.pnp.PNPROMessageRequest.processMessage(PNPROMessageRequest.java:102)
	at org.objectweb.proactive.extensions.pnp.PNPServerHandler$RequestExecutor.run(PNPServerHandler.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```
